
/**
 * @internal
 *
 * Default TWS / IB Gateway hostname.
 */
export const DEFAULT_HOST = "127.0.0.1";

/**
 * @internal
 * Default TWS / IB Gateway port number.
 */
export const DEFAULT_PORT = 7496;

/**
 * @internal
 *
 * Default client id.
 */
export const DEFAULT_CLIENT_ID = 0;

/**
 * @internal
 *
 * Maximum of requests send per second.
 */
export const MAX_REQ_PER_SECOND = 40;

/**
 * @internal
 *
 * The version of this API client implementation
 */
export const CLIENT_VERSION = 66;

/**
 * @internal
 *
 * The minimum supported server version.
 */
export const MIN_SERVER_VER_SUPPORTED = 38;

/**
 * @internal
 *
 * Security type of bag contracts.
 */
export const BAG_SEC_TYPE = "BAG";

/**
 * @internal
 *
 * Outgoing message IDs.
 */
export enum OUTGOING {
  REQ_MKT_DATA = 1,
  CANCEL_MKT_DATA = 2,
  PLACE_ORDER = 3,
  CANCEL_ORDER = 4,
  REQ_OPEN_ORDERS = 5,
  REQ_ACCOUNT_DATA = 6,
  REQ_EXECUTIONS = 7,
  REQ_IDS = 8,
  REQ_CONTRACT_DATA = 9,
  REQ_MKT_DEPTH = 10,
  CANCEL_MKT_DEPTH = 11,
  REQ_NEWS_BULLETINS = 12,
  CANCEL_NEWS_BULLETINS = 13,
  SET_SERVER_LOGLEVEL = 14,
  REQ_AUTO_OPEN_ORDERS = 15,
  REQ_ALL_OPEN_ORDERS = 16,
  REQ_MANAGED_ACCTS = 17,
  REQ_FA = 18,
  REPLACE_FA = 19,
  REQ_HISTORICAL_DATA = 20,
  EXERCISE_OPTIONS = 21,
  REQ_SCANNER_SUBSCRIPTION = 22,
  CANCEL_SCANNER_SUBSCRIPTION = 23,
  REQ_SCANNER_PARAMETERS = 24,
  CANCEL_HISTORICAL_DATA = 25,
  REQ_CURRENT_TIME = 49,
  REQ_REAL_TIME_BARS = 50,
  CANCEL_REAL_TIME_BARS = 51,
  REQ_FUNDAMENTAL_DATA = 52,
  CANCEL_FUNDAMENTAL_DATA = 53,
  REQ_CALC_IMPLIED_VOLAT = 54,
  REQ_CALC_OPTION_PRICE = 55,
  CANCEL_CALC_IMPLIED_VOLAT = 56,
  CANCEL_CALC_OPTION_PRICE = 57,
  REQ_GLOBAL_CANCEL = 58,
  REQ_MARKET_DATA_TYPE = 59,
  REQ_POSITIONS = 61,
  REQ_ACCOUNT_SUMMARY = 62,
  CANCEL_ACCOUNT_SUMMARY = 63,
  CANCEL_POSITIONS = 64,
  VERIFY_REQUEST = 65,
  VERIFY_MESSAGE = 66,
  QUERY_DISPLAY_GROUPS = 67,
  SUBSCRIBE_TO_GROUP_EVENTS = 68,
  UPDATE_DISPLAY_GROUP = 69,
  UNSUBSCRIBE_FROM_GROUP_EVENTS = 70,
  START_API = 71,
  VERIFY_AND_AUTH_REQUEST = 72,
  VERIFY_AND_AUTH_MESSAGE = 73,
  REQ_POSITIONS_MULTI = 74,
  CANCEL_POSITIONS_MULTI = 75,
  REQ_ACCOUNT_UPDATES_MULTI = 76,
  CANCEL_ACCOUNT_UPDATES_MULTI = 77,
  REQ_SEC_DEF_OPT_PARAMS = 78,
  REQ_SOFT_DOLLAR_TIERS = 79,
  REQ_FAMILY_CODES = 80,
  REQ_MATCHING_SYMBOLS = 81,
  REQ_MKT_DEPTH_EXCHANGES = 82,
  REQ_SMART_COMPONENTS = 83,
  REQ_NEWS_ARTICLE = 84,
  REQ_NEWS_PROVIDERS = 85,
  REQ_HISTORICAL_NEWS = 86,
  REQ_HEAD_TIMESTAMP = 87,
  REQ_HISTOGRAM_DATA = 88,
  CANCEL_HISTOGRAM_DATA = 89,
  REQ_PNL = 92,
  CANCEL_PNL = 93,
  REQ_PNL_SINGLE = 94,
  CANCEL_PNL_SINGLE = 95, // not implemented
  REQ_HISTORICAL_TICKS = 96,
  REQ_TICK_BY_TICK_DATA = 97,
  CANCEL_TICK_BY_TICK_DATA = 98
}

/**
 * @internal
 *
 * Minimum required server version for supporting the given request.
 */
export enum MIN_SERVER_VER {
  REAL_TIME_BARS = 34,
  SCALE_ORDERS = 35,
  SNAPSHOT_MKT_DATA = 35,
  SSHORT_COMBO_LEGS = 35,
  WHAT_IF_ORDERS = 36,
  CONTRACT_CONID = 37,
  PTA_ORDERS = 39,
  FUNDAMENTAL_DATA = 40,
  UNDER_COMP = 40,
  CONTRACT_DATA_CHAIN = 40,
  SCALE_ORDERS2 = 40,
  ALGO_ORDERS = 41,
  EXECUTION_DATA_CHAIN = 42,
  NOT_HELD = 44,
  SEC_ID_TYPE = 45,
  PLACE_ORDER_CONID = 46,
  REQ_MKT_DATA_CONID = 47,
  REQ_CALC_IMPLIED_VOLAT = 49,
  CANCEL_CALC_IMPLIED_VOLAT = 50,
  CANCEL_CALC_OPTION_PRICE = 50,
  REQ_CALC_OPTION_PRICE = 50,
  SSHORTX_OLD = 51,
  SSHORTX = 52,
  REQ_GLOBAL_CANCEL = 53,
  HEDGE_ORDERS = 54,
  REQ_MARKET_DATA_TYPE = 55,
  OPT_OUT_SMART_ROUTING = 56,
  SMART_COMBO_ROUTING_PARAMS = 57,
  DELTA_NEUTRAL_CONID = 58,
  SCALE_ORDERS3 = 60,
  ORDER_COMBO_LEGS_PRICE = 61,
  TRAILING_PERCENT = 62,
  DELTA_NEUTRAL_OPEN_CLOSE = 66,
  POSITIONS = 67,
  ACCT_SUMMARY = 67,
  TRADING_CLASS = 68,
  SCALE_TABLE = 69,
  LINKING = 70,
  ALGO_ID = 71,
  OPTIONAL_CAPABILITIES = 72,
  ORDER_SOLICITED = 73,
  LINKING_AUTH = 74,
  PRIMARYEXCH = 75,
  RANDOMIZE_SIZE_AND_PRICE = 76,
  FRACTIONAL_POSITIONS = 101,
  PEGGED_TO_BENCHMARK = 102,
  MODELS_SUPPORT = 103,
  SEC_DEF_OPT_PARAMS_REQ = 104,
  EXT_OPERATOR = 105,
  SOFT_DOLLAR_TIER = 106,
  REQ_FAMILY_CODES = 107,
  REQ_MATCHING_SYMBOLS = 108,
  PAST_LIMIT = 109,
  MD_SIZE_MULTIPLIER = 110,
  CASH_QTY = 111,
  REQ_MKT_DEPTH_EXCHANGES = 112,
  TICK_NEWS = 113,
  REQ_SMART_COMPONENTS = 114,
  REQ_NEWS_PROVIDERS = 115,
  REQ_NEWS_ARTICLE = 116,
  REQ_HISTORICAL_NEWS = 117,
  REQ_HEAD_TIMESTAMP = 118,
  REQ_HISTOGRAM = 119,
  SERVICE_DATA_TYPE = 120,
  AGG_GROUP = 121,
  UNDERLYING_INFO = 122,
  CANCEL_HEADTIMESTAMP = 123,
  SYNT_REALTIME_BARS = 124,
  CFD_REROUTE = 125,
  MARKET_RULES = 126,
  PNL = 127,
  NEWS_QUERY_ORIGINS = 128,
  UNREALIZED_PNL = 129,
  MIN_SERVER_VER_HISTORICAL_TICKS = 130,
  MARKET_CAP_PRICE = 131,
  PRE_OPEN_BID_ASK = 132,
  REAL_EXPIRATION_DATE = 134,
  REALIZED_PNL = 135,
  LAST_LIQUIDITY = 136,
  TICK_BY_TICK = 137,
  DECISION_MAKER = 138,
  MIFID_EXECUTION = 139,
  TICK_BY_TICK_IGNORE_SIZE = 140,
  AUTO_PRICE_FOR_HEDGE = 141,
  WHAT_IF_EXT_FIELDS = 142,
  SCANNER_GENERIC_OPTS = 143,
  API_BIND_ORDER = 144,
  ORDER_CONTAINER = 145,
  SMART_DEPTH = 146,
  REMOVE_NULL_ALL_CASTING = 147,
  D_PEG_ORDERS = 148,
  MKT_DEPTH_PRIM_EXCHANGE = 149,
  REQ_COMPLETED_ORDERS = 150,
  PRICE_MGMT_ALGO = 151
}

