name: "publish"

on:
  push:
    branches:
      - "master"

permissions:
  contents: read

jobs:
  bump-version:
    name: "bump version"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      # Setup Node.js
      - name: "Setup Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "yarn" # caches the yarn cache folder not node_modules

      # Automated Version Bump
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@215e27a882516826c59df7f09da8c67d5f375cbd"
        with:
          tag-prefix: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: "publish"
    needs: bump-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v6
        with:
          ref: master

      # Install packages with yarn
      - name: "Setup Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - name: "Install"
        run: yarn install --frozen-lockfile

      # Publish the package
      - name: "Publishing to Npm registry"
        run: npm publish
        env:
          CI: true
